-
  alt: Bytemark Hosting
  website: www.bytemark.co.uk
  logo: bytemark.png
-
  alt: Freelance Total - Easier Freelancing
  website: www.freelancetotal.com
  logo: ft.png
-
  alt: RubyMine — The Most Intelligent Ruby on Rails IDE
  website: www.jetbrains.com/ruby/
  logo: rubymine.png
-
  alt: MindMeister - Collaborative Mind Mapping
  website: www.mindmeister.com
  logo: mm.png
-
  alt: Heroku - Instant Ruby Platform
  website: www.heroku.com
  logo: heroku.png
-
  alt: GitHub - Social Coding
  website: www.github.com
  logo: gh.png
-
  alt: Screencasts on Behavior Driven Development techniques
  website: www.bddcasts.com
  logo: bdd.png
-
  alt: PeepCode Screencasts
  website: peepcode.com
  logo: peepcode.png
-
  alt: ZenBe - Work Better
  website: zenbe.com
  logo: zenbe.png
-
  alt: RackSpace Cloud
  website: www.rackspacecloud.com
  logo: rackspace.png
-
  alt: The Easiest Way to Sell Subscriptions on Your Site
  website: spreedly.com
  logo: spreedly.png
-
  alt: Ready-made Rails Code
  website: railskits.com
  logo: railskits.png
-
  alt: Paul Klipp
  website: www.paulklipp.com
  logo: pklipp.png
